// Generated by CoffeeScript 1.3.3
(function() {
  var Expense, ExpenseSchema, Schema, app, express, mongoose, port, routes;

  express = require("express");

  routes = require("./routes");

  mongoose = require("mongoose");

  mongoose.connect("mongodb://localhost/mongo_data");

  app = module.exports = express.createServer();

  app.configure(function() {
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](__dirname + "/public"));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure("production", function() {
    return app.use(express.errorHandler());
  });

  Schema = mongoose.Schema;

  ExpenseSchema = new Schema({
    date: String,
    remark: String,
    price: Number
  });

  Expense = mongoose.model('Expense', ExpenseSchema);

  app.get("/", routes.index);

  app.get("/expenses", function(req, res) {
    var query;
    query = Expense.find({});
    query.sort("date", 1);
    return query.exec(function(error, expenses) {
      if (!error) {
        return res.json(expenses);
      } else {
        return res.json({
          success: false
        });
      }
    });
  });

  app.post("/expenses", function(req, res) {
    var expense;
    expense = new Expense(req.body);
    return expense.save(function(error) {
      if (!error) {
        return res.json({
          success: true
        });
      } else {
        return res.json({
          success: false
        });
      }
    });
  });

  app.put("/todos/:id", function(req, res) {
    var data;
    data = {
      title: req.body.title,
      done: req.body.done
    };
    return Todo.update({
      _id: req.params.id
    }, data, function(error, todo) {
      if (!error) {
        return res.json({
          success: true
        });
      } else {
        return res.json({
          success: false
        });
      }
    });
  });

  app["delete"]("/todos/:id", function(req, res) {
    return Todo.findById(req.params.id, function(error, todo) {
      if (!error) {
        return todo.remove(function(delete_error) {
          if (!delete_error) {
            return res.json({
              success: true
            });
          } else {
            return res.json({
              success: false
            });
          }
        });
      } else {
        return res.json({
          success: false
        });
      }
    });
  });

  port = process.env.PORT || 3000;

  app.listen(port, function() {
    return console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
  });

}).call(this);
